---
# K3s configuration
k3s_version: "v1.33.1+k3s1"

# Explicit kubeconfig path
local_home: "{{ lookup('env', 'HOME') }}"
k8s_kubeconfig_path: "{{ local_home }}/.kube/config-k3s"

# K3s settings
k3s_server_args:
  - "--tls-san={{ ansible_host }}"
  - "--tls-san={{ domain_name }}"
