---
# SSH Configuration
ssh_port: "22"
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_allow_users: []  # List of allowed SSH users

# Firewall Configuration
ufw_enabled: true
ufw_allow_ports:
  - "{{ ssh_port }}"
  - "80"   # HTTP for Let's Encrypt
  - "443"  # HTTPS
  - "6443" # Kubernetes API
  - "2379" # etcd client port
  - "2380" # etcd peer port

# Fail2ban Configuration
fail2ban_enabled: true
fail2ban_bantime: "1h"
fail2ban_findtime: "1h"
fail2ban_maxretry: 3

# Sysctl Security Settings
sysctl_security:
  # Protect against IP spoofing
  net.ipv4.conf.all.rp_filter: 1
  net.ipv4.conf.default.rp_filter: 1
  # Protect against SYN flood attacks
  net.ipv4.tcp_syncookies: 1
  # IPv4 traffic forwarding (required for k3s)
  net.ipv4.ip_forward: 1
  # IPv6 traffic forwarding (required for k3s)
  net.ipv6.conf.all.forwarding: 1
