---
- name: Download Helm installer script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0700'
  become: true

- name: Install Helm
  command: /tmp/get_helm.sh
  become: true

- name: Remove Helm installer
  file:
    path: /tmp/get_helm.sh
    state: absent
  become: true

- name: Add cert-manager helm repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  become: true

- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: jetstack/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    values:
      installCRDs: true
  become: true

- name: Wait for cert-manager to be ready
  kubernetes.core.k8s:
    kind: Deployment
    name: cert-manager
    namespace: cert-manager
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    wait: yes
    wait_timeout: 300
  become: true

- name: Create Cloudflare API token secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition: "{{ lookup('template', 'cloudflare-secret.yaml.j2') | from_yaml }}"
  become: true

- name: Create ClusterIssuer
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition: "{{ lookup('template', 'cluster-issuer.yaml.j2') | from_yaml }}"
  become: true
