---
- name: Create directory for k3s manifests
  file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    mode: '0755'
  become: true

- name: Configure Traefik
  template:
    src: traefik-config.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/traefik-config.yaml
    mode: '0644'
  become: true

- name: Wait for Traefik pods to be ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: kube-system
    label_selectors:
      - app=traefik
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  register: traefik_pods
  until: 
    - traefik_pods.resources is defined
    - traefik_pods.resources | length > 0
    - traefik_pods.resources[0].status.phase == "Running"
  retries: 30
  delay: 10
  become: true

- name: Show Traefik status
  command: kubectl get pods,svc -n kube-system -l app=traefik
  become: true
  register: traefik_status

- name: Display Traefik status
  debug:
    var: traefik_status.stdout_lines
